### PR TITLE
upgraded to the latest Coveralls plugin

### PR DESCRIPTION
**Pull request by musketyr**
which support GitHub actions

### CODE REVIEW

**Comment by aalmiray** [comment]
Unfortunately `coveralls-2.9.0` is not available from JCenter/Bintray. You'll have to configure `gradlePluginPortal` in the repositories block to get it. Moreover, wouldn't this update bring trouble with the `versioning` plugin due to jgit?

**Comment by musketyr** [comment]
you are probably right, I've got settled by manually forcing `org.eclipse.jgit:org.eclipse.jgit:5.3.6.201910020505-r` which works for me. I've lost track which plugins are breaking each other. so we also need #212 resolved first

**Comment by musketyr** [comment]
is  adding `gradlePluginPortal()` a big deal? I'm already using it to grab Kordamp itself

**Comment by aalmiray** [comment]
Not really, no. It's already declared in the root `build.gradle` file so we're good in that regard however the coordinates are not resolving as they should. It may be necessary to switch to the plugin marker coordinates.

https://github.com/kordamp/kordamp-gradle-plugins/blob/master/build.gradle#L120

**Pull request merged**
